"""add transfer and merge history tables

Revision ID: 45f3fb1dc4e9
Revises: bdc4029c0da6
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45f3fb1dc4e9"
down_revision: Union[str, Sequence[str], None] = "bdc4029c0da6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_transfer_history",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "from_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "from_branch_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "to_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "to_branch_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "transfer_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "transferred_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "transferred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "is_reversed",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "reversed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "reversed_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_branch_id"],
            ["branches.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_branch_id"],
            ["branches.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transferred_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
    )

    op.create_index(
        "ix_user_transfer_history_user_id",
        "user_transfer_history",
        ["user_id"],
    )
    op.create_index(
        "ix_user_transfer_history_from_institute_id",
        "user_transfer_history",
        ["from_institute_id"],
    )
    op.create_index(
        "ix_user_transfer_history_from_branch_id",
        "user_transfer_history",
        ["from_branch_id"],
    )
    op.create_index(
        "ix_user_transfer_history_to_institute_id",
        "user_transfer_history",
        ["to_institute_id"],
    )
    op.create_index(
        "ix_user_transfer_history_to_branch_id",
        "user_transfer_history",
        ["to_branch_id"],
    )
    op.create_index(
        "ix_user_transfer_history_transfer_type",
        "user_transfer_history",
        ["transfer_type"],
    )
    op.create_index(
        "ix_user_transfer_history_transferred_by",
        "user_transfer_history",
        ["transferred_by"],
    )
    op.create_index(
        "ix_user_transfer_history_reversed_by",
        "user_transfer_history",
        ["reversed_by"],
    )

    op.create_table(
        "branch_transfer_history",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "branch_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "from_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "to_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "transferred_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "transferred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "is_reversed",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "reversed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "reversed_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["from_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["to_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["transferred_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
    )

    op.create_index(
        "ix_branch_transfer_history_branch_id",
        "branch_transfer_history",
        ["branch_id"],
    )
    op.create_index(
        "ix_branch_transfer_history_from_institute_id",
        "branch_transfer_history",
        ["from_institute_id"],
    )
    op.create_index(
        "ix_branch_transfer_history_to_institute_id",
        "branch_transfer_history",
        ["to_institute_id"],
    )
    op.create_index(
        "ix_branch_transfer_history_transferred_by",
        "branch_transfer_history",
        ["transferred_by"],
    )
    op.create_index(
        "ix_branch_transfer_history_reversed_by",
        "branch_transfer_history",
        ["reversed_by"],
    )

    op.create_table(
        "branch_merge_history",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(),
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "source_branch_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "target_branch_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "source_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "target_institute_id",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "merged_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "merged_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "reversed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "reversed_by",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_branch_id"],
            ["branches.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_branch_id"],
            ["branches.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_institute_id"],
            ["institutes.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merged_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by"],
            ["users.id"],
            ondelete="SET NULL",
        ),
    )

    op.create_index(
        "ix_branch_merge_history_source_branch_id",
        "branch_merge_history",
        ["source_branch_id"],
    )
    op.create_index(
        "ix_branch_merge_history_target_branch_id",
        "branch_merge_history",
        ["target_branch_id"],
    )
    op.create_index(
        "ix_branch_merge_history_source_institute_id",
        "branch_merge_history",
        ["source_institute_id"],
    )
    op.create_index(
        "ix_branch_merge_history_target_institute_id",
        "branch_merge_history",
        ["target_institute_id"],
    )
    op.create_index(
        "ix_branch_merge_history_merged_by",
        "branch_merge_history",
        ["merged_by"],
    )
    op.create_index(
        "ix_branch_merge_history_status",
        "branch_merge_history",
        ["status"],
    )
    op.create_index(
        "ix_branch_merge_history_reversed_by",
        "branch_merge_history",
        ["reversed_by"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_branch_merge_history_reversed_by",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_status",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_merged_by",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_target_institute_id",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_source_institute_id",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_target_branch_id",
        table_name="branch_merge_history",
    )
    op.drop_index(
        "ix_branch_merge_history_source_branch_id",
        table_name="branch_merge_history",
    )
    op.drop_table("branch_merge_history")

    op.drop_index(
        "ix_branch_transfer_history_reversed_by",
        table_name="branch_transfer_history",
    )
    op.drop_index(
        "ix_branch_transfer_history_transferred_by",
        table_name="branch_transfer_history",
    )
    op.drop_index(
        "ix_branch_transfer_history_to_institute_id",
        table_name="branch_transfer_history",
    )
    op.drop_index(
        "ix_branch_transfer_history_from_institute_id",
        table_name="branch_transfer_history",
    )
    op.drop_index(
        "ix_branch_transfer_history_branch_id",
        table_name="branch_transfer_history",
    )
    op.drop_table("branch_transfer_history")

    op.drop_index(
        "ix_user_transfer_history_reversed_by",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_transferred_by",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_transfer_type",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_to_branch_id",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_to_institute_id",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_from_branch_id",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_from_institute_id",
        table_name="user_transfer_history",
    )
    op.drop_index(
        "ix_user_transfer_history_user_id",
        table_name="user_transfer_history",
    )
    op.drop_table("user_transfer_history")