"""add branch institute code unique constraint

Revision ID: bdc4029c0da6
Revises: 7b164ae294ac
Create Date: 2026-09-05 07:40:25.511146
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc4029c0da6'
down_revision: Union[str, None] = '7b164ae294ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_branches_institute_code', 'branches', ['institute_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_branches_institute_code', 'branches', type_='unique')
    # ### end Alembic commands ###